"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Upload, Download, Eye, Plus } from "lucide-react";

const certificates = [
  {
    id: 1,
    studentName: "John Doe",
    courseName: "Web Development Basics",
    certificateId: "WDF-2024-001",
    issuedDate: "2024-01-15",
    status: "issued",
    grade: "A",
    autoGenerated: true,
  },
  {
    id: 2,
    studentName: "Jane Smith",
    courseName: "Advanced React Development",
    certificateId: "ARD-2024-002",
    issuedDate: "2024-01-20",
    status: "issued",
    grade: "A+",
    autoGenerated: true,
  },
  {
    id: 3,
    studentName: "David Brown",
    courseName: "Database Management Systems",
    certificateId: "DMS-2024-003",
    issuedDate: "2024-01-22",
    status: "issued",
    grade: "B+",
    autoGenerated: false,
  },
  {
    id: 4,
    studentName: "Sarah Wilson",
    courseName: "Python for Data Science",
    certificateId: "PDS-2024-004",
    issuedDate: null,
    status: "pending",
    grade: null,
    autoGenerated: true,
  },
];

const students = [
  { id: 1, name: "John Doe", email: "john.doe@email.com" },
  { id: 2, name: "Jane Smith", email: "jane.smith@email.com" },
  { id: 3, name: "David Brown", email: "david.brown@email.com" },
  { id: 4, name: "Sarah Wilson", email: "sarah.wilson@email.com" },
];

const courses = [
  { id: 1, name: "Web Development Basics" },
  { id: 2, name: "Advanced React Development" },
  { id: 3, name: "Database Management Systems" },
  { id: 4, name: "Python for Data Science" },
];

export function CertificateManagementTab() {
  const [isUploadDialogOpen, setIsUploadDialogOpen] = useState(false);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">
            Certificate Management
          </h2>
          <p className="text-gray-600">
            Manage and issue certificates to students
          </p>
        </div>
        <Dialog open={isUploadDialogOpen} onOpenChange={setIsUploadDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="h-4 w-4 mr-2" />
              Issue Certificate
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Issue New Certificate</DialogTitle>
              <DialogDescription>
                Manually issue a certificate to a student
              </DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <div className="space-y-2">
                <Label htmlFor="student">Student</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a student" />
                  </SelectTrigger>
                  <SelectContent>
                    {students.map((student) => (
                      <SelectItem
                        key={student.id}
                        value={student.id.toString()}
                      >
                        {student.name} ({student.email})
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="course">Course</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a course" />
                  </SelectTrigger>
                  <SelectContent>
                    {courses.map((course) => (
                      <SelectItem key={course.id} value={course.id.toString()}>
                        {course.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="grade">Grade</Label>
                <Select>
                  <SelectTrigger>
                    <SelectValue placeholder="Select grade" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="A+">A+</SelectItem>
                    <SelectItem value="A">A</SelectItem>
                    <SelectItem value="B+">B+</SelectItem>
                    <SelectItem value="B">B</SelectItem>
                    <SelectItem value="C+">C+</SelectItem>
                    <SelectItem value="C">C</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2">
                <Label htmlFor="certificate-file">
                  Upload Certificate (Optional)
                </Label>
                <div className="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
                  <Upload className="h-8 w-8 text-gray-400 mx-auto mb-2" />
                  <p className="text-sm text-gray-600">
                    Drag and drop a certificate file, or click to browse
                  </p>
                  <Input
                    type="file"
                    className="hidden"
                    accept=".pdf,.jpg,.png"
                  />
                </div>
              </div>
              <div className="flex justify-end space-x-2">
                <Button
                  variant="outline"
                  onClick={() => setIsUploadDialogOpen(false)}
                >
                  Cancel
                </Button>
                <Button onClick={() => setIsUploadDialogOpen(false)}>
                  Issue Certificate
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Stats Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-blue-600">
              {certificates.length}
            </div>
            <div className="text-sm text-gray-600">Total Certificates</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-green-600">
              {certificates.filter((c) => c.status === "issued").length}
            </div>
            <div className="text-sm text-gray-600">Issued</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-yellow-600">
              {certificates.filter((c) => c.status === "pending").length}
            </div>
            <div className="text-sm text-gray-600">Pending</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="text-2xl font-bold text-purple-600">
              {certificates.filter((c) => c.autoGenerated).length}
            </div>
            <div className="text-sm text-gray-600">Auto-Generated</div>
          </CardContent>
        </Card>
      </div>

      {/* Certificates Table */}
      <Card>
        <CardHeader>
          <CardTitle>All Certificates</CardTitle>
          <CardDescription>View and manage issued certificates</CardDescription>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Student</TableHead>
                <TableHead>Course</TableHead>
                <TableHead>Certificate ID</TableHead>
                <TableHead>Grade</TableHead>
                <TableHead>Issue Date</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Type</TableHead>
                <TableHead className="text-right">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {certificates.map((certificate) => (
                <TableRow key={certificate.id}>
                  <TableCell className="font-medium">
                    {certificate.studentName}
                  </TableCell>
                  <TableCell>{certificate.courseName}</TableCell>
                  <TableCell>
                    <code className="text-xs bg-gray-100 px-2 py-1 rounded">
                      {certificate.certificateId}
                    </code>
                  </TableCell>
                  <TableCell>
                    {certificate.grade && (
                      <Badge
                        variant="outline"
                        className="bg-green-50 text-green-700 border-green-200"
                      >
                        {certificate.grade}
                      </Badge>
                    )}
                  </TableCell>
                  <TableCell>{certificate.issuedDate || "—"}</TableCell>
                  <TableCell>
                    <Badge
                      variant={
                        certificate.status === "issued"
                          ? "default"
                          : "secondary"
                      }
                      className={
                        certificate.status === "issued"
                          ? "bg-green-100 text-green-800"
                          : "bg-yellow-100 text-yellow-800"
                      }
                    >
                      {certificate.status.charAt(0).toUpperCase() +
                        certificate.status.slice(1)}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <Badge variant="outline">
                      {certificate.autoGenerated ? "Auto" : "Manual"}
                    </Badge>
                  </TableCell>
                  <TableCell className="text-right">
                    <div className="flex justify-end space-x-1">
                      <Button variant="ghost" size="sm">
                        <Eye className="h-4 w-4" />
                      </Button>
                      {certificate.status === "issued" && (
                        <Button variant="ghost" size="sm">
                          <Download className="h-4 w-4" />
                        </Button>
                      )}
                    </div>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
